### ISSUE TITLE
咨询一下，是否支持goctls api new 命令时自动化生成Info结构体

### ISSUE THREAD

**Issue by franktrue** [suyuan32/simple-admin-example-api#1]
![image](https://user-images.githubusercontent.com/10108380/231398810-597d7b7a-881d-4ee9-86ae-f24f4fca3ac2.png)
如图所示目前生成的.api文件中的info结构体仅有BaseIDInfo，后续是否会扩展支持根据ent生成字段信息

**Comment by suyuan32** [comment]
是支持的，不过近期更改了依赖，有点问题，建议先用 release版本

**Comment by franktrue** [comment]
好的，我试一下，多谢

**Comment by suyuan32** [comment]
用simple admin tools 0.3.2 的 release 版本就没事，最新的代码升级了 ent ，有点问题

**Comment by franktrue** [comment]
goctls api new 生成Info是可以了，但是正常的RPC服务重新生成后运行报错，类似下面这种
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/10108380/231418246-bd3cde5d-a175-4f1b-8034-cec173633cf7.png">
然后我又切回master了

**Comment by suyuan32** [comment]
稍等下哈，我们正在修复bug，我待会测试下

**Comment by suyuan32** [comment]
https://doc.ryansu.pro/zh/guide/quick-start/extra/ent_template.html

**Comment by suyuan32** [comment]
> goctls api new 生成Info是可以了，但是正常的RPC服务重新生成后运行报错，类似下面这种 <img alt="image" width="1031" src="https://user-images.githubusercontent.com/10108380/231418246-bd3cde5d-a175-4f1b-8034-cec173633cf7.png"> 然后我又切回master了

你这个错误是要更新模板

**Comment by suyuan32** [comment]
@franktrue

**Comment by suyuan32** [comment]
不过更新模板是最新代码才有的功能，再等一会我测试下吧，看下api proto 有啥bug

**Comment by franktrue** [comment]
好的，辛苦大佬

**Comment by suyuan32** [comment]
我测试了下最新代码，好像没问题，你pull最新试试 @franktrue

**Comment by suyuan32** [comment]
有问题的话提供下复现步骤

**Comment by suyuan32** [comment]
根据 example 项目的命令来一遍，检查下有啥区别

**Comment by suyuan32** [comment]
https://doc.ryansu.pro/zh/guide/quick-start/codegen/api_example.html#%E4%BB%A3%E7%A0%81%E7%94%9F%E6%88%90-%E5%9F%BA%E4%BA%8E-proto

**Comment by suyuan32** [comment]
还有就是检查proto文件是否正确

**Comment by franktrue** [comment]
更新到最新master 生成RPC正常的了，就是goctls new api 生成还有字段信息的info还是不行

**Comment by suyuan32** [comment]
goctls new api ?

**Comment by suyuan32** [comment]
goctls api proto吧？你的完整命令是啥？
