### ISSUE TITLE
依赖好像有点问题

### ISSUE THREAD

**Issue by call-81192** [suyuan32/simple-admin-example-api#2]
go: finding module for package github.com/zeromicro/go-zero/rest/enum
go: github.com/suyuan32/simple-admin-example-api/internal/middleware imports
        github.com/suyuan32/simple-admin-common/orm/ent/entctx/rolectx imports
        github.com/zeromicro/go-zero/rest/enum: module github.com/zeromicro/go-zero@latest found (v1.6.6), but does not contain package github.com/zeromicro/go-zero/rest/enum

======================
版本号
go version go1.22.5 windows/amd64
goctls version v1.7.14 windows/amd64 - Go Zero v1.6.6 - Simple Admin Tools v1.6.15
======================
执行
goctls api new user -i -c -a -m github.com/suyuan32/simple-admin-example-api -p 8081 -e 
cd user
go mod tidy

**Comment by call-81192** [comment]
在mod中手动添加replace github.com/zeromicro/go-zero v1.6.6 => github.com/suyuan32/simple-admin-tools v1.6.15
就正常了

**Comment by suyuan32** [comment]
是 Bug ，将工具升级至 v1.7.15

**Comment by suyuan32** [comment]
go install github.com/suyuan32/goctls@v1.7.15
